---
title: "Challenge B in R Programming"
author: "D. Goninet & D. Lachiver"
date: "25 novembre 2017"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages("readr", contriburl = "https://cloud.r-project.org")
install.packages("class", contriburl = "https://cloud.r-project.org")
install.packages('np', dependencies = TRUE)
library(readr)
library(class)
library(np)
library(tidyverse)
```

Our Github repository : 
"https://github.com/doriangoninet/RProgChallengeB"

# Task 1B

```{r 1B.setup, include = FALSE}
# importing data
train <- read_csv("train.csv")
test <- read.csv("test.csv")
```

## Step 1

We chose the K-Nearest Neighbour - called KNN lower.
USE package "knncat" for categorical & continous variables.

## Step 2

```{r 1B.step2.setup, echo = TRUE}
#Convert character to factors 
sapply(train, class)
train[sapply(train, is.character)] <- lapply(train[sapply(train, is.character)], as.factor)
sapply(train, class)
```

```{r 1B.step2, include = TRUE}
model1 <- npreg(SalePrice ~ MSZoning + LotArea + Neighborhood  + YearBuilt + OverallQual, data = train)
```

## Step 3

```{r}
prednp <- predict(model1, newdata = test)
write.csv(prednp, file = "sample_challengeB.csv", row.names=FALSE)

prediction_challB <- data.frame(Id = test$Id, SalePrice_predict = predict(model1, test, type="response"))
write.csv(x = prediction, file = "predictions_challB.csv", na = "NA", quote = FALSE, row.names = FALSE)
```